name: build-app
on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      sha:
        required: false
        type: string
      version:
        required: false
        type: string
      target_env:
        required: false
        type: string
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Stub build-app
        run: |
          echo "build-app environment=${{ inputs.environment }} sha=${{ inputs.sha }} version=${{ inputs.version }} target_env=${{ inputs.target_env }}"
          sleep 2
